# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20170927_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.FileField(null=True, upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Specify url', unique=True),
        ),
    ]
